#!/usr/bin/zsh
source ${0:a:h}/env

[ -d "$SERVER_PATH/mods" ] && [ $(ls "$SERVER_PATH/mods" | wc -l) -gt 0 ] \
	|| { echo '\033[31mNo mods active\033[0m'; exit 1 }

MOD_NAME=$(\
	ls "$SERVER_PATH/mods"\
	| fzf $FZF_OPTIONS --prompt 'choose a mod to deactivate : '\
)

[ ! $MOD_NAME ] && exit 2;

rm "$SERVER_PATH/mods/$MOD_NAME" 2>/dev/null \
	&& echo "\\033[92mSuccessfully devactivated mod '$MOD_NAME'\\033[0m" \
	|| echo "\\033[31mError deactivating mod. Check mod folder read/write permissions.\\033[0m" \
	;
