#!/bin/zsh
source ./env

echo '\033[33mGetting version information\033[0m'
VERSION_MANIFEST=$(wget -O - "$VERSION_MANIFEST_URL" 2>/dev/null)
[ ! "$VERSION_MANIFEST" ] && {
	echo '\033[31mUnable to obtain version manifest\033[0m';
	exit 2;
}

VERSION=$(echo "$VERSION_MANIFEST" | jq ".versions[] | .id" -r | fzf $FZF_OPTIONS --prompt='select version : ')
[ ! "$VERSION" ] && {
	echo '\033[31mNo version selected\033[0m';
	exit 3;
}

VERSION_URL=$(echo "$VERSION_MANIFEST" | jq ".versions[] | select(.id == \"$VERSION\") | .url" -r)

[ ! "$VERSION_URL" ] && {
	echo '\033[31mUnable to obtain version data from manifest\033[0m';
	exit 4;
}

echo "\\033[32mLatest Version : \\033[35m$LATEST_VERSION\\033[0m"

LOCAL_JAR="$VERSIONS_PATH/$VERSION.jar"
[ -f "$LOCAL_JAR" ] && {
	echo "\\033[92mVersion $VERSION already installed\\033[0m"
} || {
	echo '\033[33mDownloading version executable...\033[0m'
	DOWNLOAD_URL=$(wget -O - "$VERSION_URL" 2>/dev/null | jq .downloads.server.url -r)

	wget -O "$LOCAL_JAR" "$DOWNLOAD_URL" 2>/dev/null\
		&& echo "\\033[32mSuccessfully downloaded version $LATEST_VERSION\\033[0m"\
		|| { echo "\\033[31mError downloading from '$DOWNLOAD_URL'\\033[0m"; exit 5 };
}

echo "\\033[33mInstalling version...\\033[0m"
rm "$SERVER_JAR" 2>/dev/null;
ln -s "$LOCAL_JAR" "$SERVER_JAR" \
	&& echo "\\033[92mSuccessfully installed version $LATEST_VERSION\\033[0m" \
	|| echo "\\033[31mError installing server.jar. Check symlink location.\\033[0m";
